### PR TITLE
Fix changelog formatting

### PR DESCRIPTION
**Pull request by chris-erickson**
### Summary & motivation

Formatting was broken

### CODE REVIEW

**Comment by dweedon-stripe** [comment]
@chris-erickson can you rebase master? I had to modify the travis config.

**Comment by chris-erickson** [comment]
@dweedon-stripe should be all set now

**Comment by dweedon-stripe** [comment]
Looks like you need to run `yarn prettier`

**Comment by chris-erickson** [comment]
@dweedon-stripe took me a while but I think I got it now.

**Pull request merged**
